# Global configuration file

dataset:
  name: "SRDdev/AI-TextImageEdit"
  split: "V1"
  limit: 105

paths:
  data_dir: "data/"
  experiments_dir: "experiments/"

logging:
  level: "DEBUG"

models:
  watermarking:
    - "watermarkanything"
    - "wm_model2"
  editing:
    - "instructpix2pix"
    - "edit_model2"
  detection:
    - "detector1"

#---------------------------------------------------------#
instructpix2pix:
  config_path: "external/instructpix2pix/configs/generate.yaml"
  resolution: 512
  steps: 100
  cfg_text: 7.5
  cfg_image: 1.5
  ckpt_path: "external/instructpix2pix/checkpoints/instruct-pix2pix-00-22000.ckpt"
  vae_ckpt_path: null